// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: push.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HYFServer {

  /// <summary>Holder for reflection information generated from push.proto</summary>
  public static partial class PushReflection {

    #region Descriptor
    /// <summary>File descriptor for push.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PushReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpwdXNoLnByb3RvEgRwdXNoGgpyb2xlLnByb3RvGgliYWcucHJvdG8iCQoH",
            "UHVzaFJlcSJtCgdQdXNoUnNwEjAKD3JvbGVMZXZlbFVwZGF0ZRgCIAEoCzIV",
            "LnJvbGUuUm9sZUxldmVsVXBkYXRlSAASIQoIaXRlbURvdHMYBCABKAsyDS5i",
            "YWcuSXRlbUR0b3NIAEINCgtQdXNoTWVzc2FnZTI7CgtQdXNoU2VydmljZRIs",
            "CgpTZXJ2ZXJQdXNoEg0ucHVzaC5QdXNoUmVxGg0ucHVzaC5QdXNoUnNwMAFC",
            "DKoCCUhZRlNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HYFServer.RoleReflection.Descriptor, global::HYFServer.BagReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HYFServer.PushReq), global::HYFServer.PushReq.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HYFServer.PushRsp), global::HYFServer.PushRsp.Parser, new[]{ "RoleLevelUpdate", "ItemDots" }, new[]{ "PushMessage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PushReq : pb::IMessage<PushReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushReq> _parser = new pb::MessageParser<PushReq>(() => new PushReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PushReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HYFServer.PushReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushReq(PushReq other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushReq Clone() {
      return new PushReq(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PushReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PushReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PushReq other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class PushRsp : pb::IMessage<PushRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushRsp> _parser = new pb::MessageParser<PushRsp>(() => new PushRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PushRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HYFServer.PushReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushRsp(PushRsp other) : this() {
      switch (other.PushMessageCase) {
        case PushMessageOneofCase.RoleLevelUpdate:
          RoleLevelUpdate = other.RoleLevelUpdate.Clone();
          break;
        case PushMessageOneofCase.ItemDots:
          ItemDots = other.ItemDots.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushRsp Clone() {
      return new PushRsp(this);
    }

    /// <summary>Field number for the "roleLevelUpdate" field.</summary>
    public const int RoleLevelUpdateFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HYFServer.RoleLevelUpdate RoleLevelUpdate {
      get { return pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate ? (global::HYFServer.RoleLevelUpdate) pushMessage_ : null; }
      set {
        pushMessage_ = value;
        pushMessageCase_ = value == null ? PushMessageOneofCase.None : PushMessageOneofCase.RoleLevelUpdate;
      }
    }

    /// <summary>Field number for the "itemDots" field.</summary>
    public const int ItemDotsFieldNumber = 4;
    /// <summary>
    /// 在前面添加更多需要Push的数据类型     
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HYFServer.ItemDtos ItemDots {
      get { return pushMessageCase_ == PushMessageOneofCase.ItemDots ? (global::HYFServer.ItemDtos) pushMessage_ : null; }
      set {
        pushMessage_ = value;
        pushMessageCase_ = value == null ? PushMessageOneofCase.None : PushMessageOneofCase.ItemDots;
      }
    }

    private object pushMessage_;
    /// <summary>Enum of possible cases for the "PushMessage" oneof.</summary>
    public enum PushMessageOneofCase {
      None = 0,
      RoleLevelUpdate = 2,
      ItemDots = 4,
    }
    private PushMessageOneofCase pushMessageCase_ = PushMessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushMessageOneofCase PushMessageCase {
      get { return pushMessageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPushMessage() {
      pushMessageCase_ = PushMessageOneofCase.None;
      pushMessage_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PushRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PushRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RoleLevelUpdate, other.RoleLevelUpdate)) return false;
      if (!object.Equals(ItemDots, other.ItemDots)) return false;
      if (PushMessageCase != other.PushMessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) hash ^= RoleLevelUpdate.GetHashCode();
      if (pushMessageCase_ == PushMessageOneofCase.ItemDots) hash ^= ItemDots.GetHashCode();
      hash ^= (int) pushMessageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) {
        output.WriteRawTag(18);
        output.WriteMessage(RoleLevelUpdate);
      }
      if (pushMessageCase_ == PushMessageOneofCase.ItemDots) {
        output.WriteRawTag(34);
        output.WriteMessage(ItemDots);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) {
        output.WriteRawTag(18);
        output.WriteMessage(RoleLevelUpdate);
      }
      if (pushMessageCase_ == PushMessageOneofCase.ItemDots) {
        output.WriteRawTag(34);
        output.WriteMessage(ItemDots);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoleLevelUpdate);
      }
      if (pushMessageCase_ == PushMessageOneofCase.ItemDots) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemDots);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PushRsp other) {
      if (other == null) {
        return;
      }
      switch (other.PushMessageCase) {
        case PushMessageOneofCase.RoleLevelUpdate:
          if (RoleLevelUpdate == null) {
            RoleLevelUpdate = new global::HYFServer.RoleLevelUpdate();
          }
          RoleLevelUpdate.MergeFrom(other.RoleLevelUpdate);
          break;
        case PushMessageOneofCase.ItemDots:
          if (ItemDots == null) {
            ItemDots = new global::HYFServer.ItemDtos();
          }
          ItemDots.MergeFrom(other.ItemDots);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            global::HYFServer.RoleLevelUpdate subBuilder = new global::HYFServer.RoleLevelUpdate();
            if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) {
              subBuilder.MergeFrom(RoleLevelUpdate);
            }
            input.ReadMessage(subBuilder);
            RoleLevelUpdate = subBuilder;
            break;
          }
          case 34: {
            global::HYFServer.ItemDtos subBuilder = new global::HYFServer.ItemDtos();
            if (pushMessageCase_ == PushMessageOneofCase.ItemDots) {
              subBuilder.MergeFrom(ItemDots);
            }
            input.ReadMessage(subBuilder);
            ItemDots = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            global::HYFServer.RoleLevelUpdate subBuilder = new global::HYFServer.RoleLevelUpdate();
            if (pushMessageCase_ == PushMessageOneofCase.RoleLevelUpdate) {
              subBuilder.MergeFrom(RoleLevelUpdate);
            }
            input.ReadMessage(subBuilder);
            RoleLevelUpdate = subBuilder;
            break;
          }
          case 34: {
            global::HYFServer.ItemDtos subBuilder = new global::HYFServer.ItemDtos();
            if (pushMessageCase_ == PushMessageOneofCase.ItemDots) {
              subBuilder.MergeFrom(ItemDots);
            }
            input.ReadMessage(subBuilder);
            ItemDots = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
