
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GuideStepConfig : Luban.BeanBase
{
    public GuideStepConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GType = _buf.ReadInt();
        SortId = _buf.ReadInt();
        UiPath = _buf.ReadString();
        MoveEffect = _buf.ReadString();
        MaskLoader = _buf.ReadString();
        CloseMain = _buf.ReadInt();
        FinishTime = _buf.ReadFloat();
        DescId = _buf.ReadInt();
    }

    public static GuideStepConfig DeserializeGuideStepConfig(ByteBuf _buf)
    {
        return new GuideStepConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// type类型
    /// </summary>
    public readonly int GType;
    /// <summary>
    /// 步骤顺序
    /// </summary>
    public readonly int SortId;
    /// <summary>
    /// ui路径
    /// </summary>
    public readonly string UiPath;
    /// <summary>
    /// 手指动效名字
    /// </summary>
    public readonly string MoveEffect;
    /// <summary>
    /// mask显示
    /// </summary>
    public readonly string MaskLoader;
    /// <summary>
    /// 关闭
    /// </summary>
    public readonly int CloseMain;
    /// <summary>
    /// 完成时间
    /// </summary>
    public readonly float FinishTime;
    /// <summary>
    /// 指引文字说明
    /// </summary>
    public readonly int DescId;
   
    public const int __ID__ = -1248104150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "gType:" + GType + ","
        + "sortId:" + SortId + ","
        + "uiPath:" + UiPath + ","
        + "moveEffect:" + MoveEffect + ","
        + "maskLoader:" + MaskLoader + ","
        + "closeMain:" + CloseMain + ","
        + "finishTime:" + FinishTime + ","
        + "descId:" + DescId + ","
        + "}";
    }
}

}

