
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ItemProp : Luban.BeanBase
{
    public ItemProp(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static ItemProp DeserializeItemProp(ByteBuf _buf)
    {
        return new ItemProp(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 导表的道具数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = 1242051894;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "}";
    }
}

}

