
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        NameLangId = _buf.ReadInt();
        Icon = _buf.ReadString();
        SmallIcon = _buf.ReadString();
        Type = _buf.ReadInt();
        Quality = _buf.ReadInt();
        ShowAdd = _buf.ReadInt();
        Desc = _buf.ReadString();
        DescLangId = _buf.ReadInt();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具翻译id
    /// </summary>
    public readonly int NameLangId;
    /// <summary>
    /// 道具图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具小图标
    /// </summary>
    public readonly string SmallIcon;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 是否显示加号
    /// </summary>
    public readonly int ShowAdd;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 描述翻译id
    /// </summary>
    public readonly int DescLangId;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "nameLangId:" + NameLangId + ","
        + "icon:" + Icon + ","
        + "smallIcon:" + SmallIcon + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "showAdd:" + ShowAdd + ","
        + "desc:" + Desc + ","
        + "descLangId:" + DescLangId + ","
        + "}";
    }
}

}

