
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class MainUIBtnConfig : Luban.BeanBase
{
    public MainUIBtnConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IconURL = _buf.ReadString();
        TitleTxt = _buf.ReadString();
        TType = _buf.ReadInt();
    }

    public static MainUIBtnConfig DeserializeMainUIBtnConfig(ByteBuf _buf)
    {
        return new MainUIBtnConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 按钮
    /// </summary>
    public readonly string IconURL;
    /// <summary>
    /// 底部名字
    /// </summary>
    public readonly string TitleTxt;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int TType;
   
    public const int __ID__ = 1446676753;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "iconURL:" + IconURL + ","
        + "titleTxt:" + TitleTxt + ","
        + "tType:" + TType + ","
        + "}";
    }
}

}

