
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PokerConfig : Luban.BeanBase
{
    public PokerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UrlIcon = _buf.ReadString();
        CardValue = _buf.ReadInt();
    }

    public static PokerConfig DeserializePokerConfig(ByteBuf _buf)
    {
        return new PokerConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string UrlIcon;
    /// <summary>
    /// 牌值
    /// </summary>
    public readonly int CardValue;
   
    public const int __ID__ = 1860949115;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "urlIcon:" + UrlIcon + ","
        + "cardValue:" + CardValue + ","
        + "}";
    }
}

}

