
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Pos2Int : Luban.BeanBase
{
    public Pos2Int(ByteBuf _buf) 
    {
        Xx = _buf.ReadInt();
        Yy = _buf.ReadInt();
    }

    public static Pos2Int DeserializePos2Int(ByteBuf _buf)
    {
        return new Pos2Int(_buf);
    }

    /// <summary>
    /// 位置x值
    /// </summary>
    public readonly int Xx;
    /// <summary>
    /// 位置y值
    /// </summary>
    public readonly int Yy;
   
    public const int __ID__ = 1271454353;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "xx:" + Xx + ","
        + "yy:" + Yy + ","
        + "}";
    }
}

}

