
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PuzzleConfig : Luban.BeanBase
{
    public PuzzleConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UrlMask = _buf.ReadString();
        IconPos = Pos2Int.DeserializePos2Int(_buf);
        CellPos = Pos2Int.DeserializePos2Int(_buf);
    }

    public static PuzzleConfig DeserializePuzzleConfig(ByteBuf _buf)
    {
        return new PuzzleConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 组件
    /// </summary>
    public readonly string UrlMask;
    /// <summary>
    /// icon位置
    /// </summary>
    public readonly Pos2Int IconPos;
    /// <summary>
    /// cell位置,0,0开始
    /// </summary>
    public readonly Pos2Int CellPos;
   
    public const int __ID__ = -1306596032;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        IconPos?.ResolveRef(tables);
        CellPos?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "urlMask:" + UrlMask + ","
        + "iconPos:" + IconPos + ","
        + "cellPos:" + CellPos + ","
        + "}";
    }
}

}

