
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RechargeConfig : Luban.BeanBase
{
    public RechargeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Commodity = _buf.ReadString();
        ExtraFirst = _buf.ReadString();
        RType = _buf.ReadInt();
        CenIcon = _buf.ReadString();
        Price = _buf.ReadInt();
    }

    public static RechargeConfig DeserializeRechargeConfig(ByteBuf _buf)
    {
        return new RechargeConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 商品
    /// </summary>
    public readonly string Commodity;
    /// <summary>
    /// 首充额外获得
    /// </summary>
    public readonly string ExtraFirst;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int RType;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string CenIcon;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1565007639;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "commodity:" + Commodity + ","
        + "extraFirst:" + ExtraFirst + ","
        + "rType:" + RType + ","
        + "cenIcon:" + CenIcon + ","
        + "price:" + Price + ","
        + "}";
    }
}

}

