
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SoundConfig : Luban.BeanBase
{
    public SoundConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        YooPath = _buf.ReadString();
    }

    public static SoundConfig DeserializeSoundConfig(ByteBuf _buf)
    {
        return new SoundConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string YooPath;
   
    public const int __ID__ = -1164338927;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "yooPath:" + YooPath + ","
        + "}";
    }
}

}

