
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbCfg_English
{
    private readonly System.Collections.Generic.Dictionary<int, Cfg_English> _dataMap;
    private readonly System.Collections.Generic.List<Cfg_English> _dataList;
    
    public TbCfg_English(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Cfg_English>();
        _dataList = new System.Collections.Generic.List<Cfg_English>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Cfg_English _v;
            _v = Cfg_English.DeserializeCfg_English(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Cfg_English> DataMap => _dataMap;
    public System.Collections.Generic.List<Cfg_English> DataList => _dataList;

    public Cfg_English GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cfg_English Get(int key) => _dataMap[key];
    public Cfg_English this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

