
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEffectConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EffectConfig> _dataMap;
    private readonly System.Collections.Generic.List<EffectConfig> _dataList;
    
    public TbEffectConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EffectConfig>();
        _dataList = new System.Collections.Generic.List<EffectConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EffectConfig _v;
            _v = EffectConfig.DeserializeEffectConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EffectConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EffectConfig> DataList => _dataList;

    public EffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EffectConfig Get(int key) => _dataMap[key];
    public EffectConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

