
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEightGiftConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EightGiftConfig> _dataMap;
    private readonly System.Collections.Generic.List<EightGiftConfig> _dataList;
    
    public TbEightGiftConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EightGiftConfig>();
        _dataList = new System.Collections.Generic.List<EightGiftConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EightGiftConfig _v;
            _v = EightGiftConfig.DeserializeEightGiftConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EightGiftConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EightGiftConfig> DataList => _dataList;

    public EightGiftConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EightGiftConfig Get(int key) => _dataMap[key];
    public EightGiftConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

