
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGuideStepConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GuideStepConfig> _dataMap;
    private readonly System.Collections.Generic.List<GuideStepConfig> _dataList;
    
    public TbGuideStepConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideStepConfig>();
        _dataList = new System.Collections.Generic.List<GuideStepConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuideStepConfig _v;
            _v = GuideStepConfig.DeserializeGuideStepConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideStepConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideStepConfig> DataList => _dataList;

    public GuideStepConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideStepConfig Get(int key) => _dataMap[key];
    public GuideStepConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

