
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGuideDescConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GuideDescConfig> _dataMap;
    private readonly System.Collections.Generic.List<GuideDescConfig> _dataList;
    
    public TbGuideDescConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideDescConfig>();
        _dataList = new System.Collections.Generic.List<GuideDescConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuideDescConfig _v;
            _v = GuideDescConfig.DeserializeGuideDescConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideDescConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideDescConfig> DataList => _dataList;

    public GuideDescConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideDescConfig Get(int key) => _dataMap[key];
    public GuideDescConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

