
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGuideTypeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GuideTypeConfig> _dataMap;
    private readonly System.Collections.Generic.List<GuideTypeConfig> _dataList;
    
    public TbGuideTypeConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideTypeConfig>();
        _dataList = new System.Collections.Generic.List<GuideTypeConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuideTypeConfig _v;
            _v = GuideTypeConfig.DeserializeGuideTypeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideTypeConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideTypeConfig> DataList => _dataList;

    public GuideTypeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideTypeConfig Get(int key) => _dataMap[key];
    public GuideTypeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

