
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbHeroInfoConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HeroInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<HeroInfoConfig> _dataList;
    
    public TbHeroInfoConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroInfoConfig>();
        _dataList = new System.Collections.Generic.List<HeroInfoConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HeroInfoConfig _v;
            _v = HeroInfoConfig.DeserializeHeroInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroInfoConfig> DataList => _dataList;

    public HeroInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroInfoConfig Get(int key) => _dataMap[key];
    public HeroInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

