
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbMainUIBtnConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MainUIBtnConfig> _dataMap;
    private readonly System.Collections.Generic.List<MainUIBtnConfig> _dataList;
    
    public TbMainUIBtnConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MainUIBtnConfig>();
        _dataList = new System.Collections.Generic.List<MainUIBtnConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MainUIBtnConfig _v;
            _v = MainUIBtnConfig.DeserializeMainUIBtnConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MainUIBtnConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MainUIBtnConfig> DataList => _dataList;

    public MainUIBtnConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MainUIBtnConfig Get(int key) => _dataMap[key];
    public MainUIBtnConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

