
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSoundConfig
{
    private readonly System.Collections.Generic.Dictionary<string, SoundConfig> _dataMap;
    private readonly System.Collections.Generic.List<SoundConfig> _dataList;
    
    public TbSoundConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, SoundConfig>();
        _dataList = new System.Collections.Generic.List<SoundConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SoundConfig _v;
            _v = SoundConfig.DeserializeSoundConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, SoundConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SoundConfig> DataList => _dataList;

    public SoundConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SoundConfig Get(string key) => _dataMap[key];
    public SoundConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

