
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbWelfareMenuConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WelfareMenuConfig> _dataMap;
    private readonly System.Collections.Generic.List<WelfareMenuConfig> _dataList;
    
    public TbWelfareMenuConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WelfareMenuConfig>();
        _dataList = new System.Collections.Generic.List<WelfareMenuConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WelfareMenuConfig _v;
            _v = WelfareMenuConfig.DeserializeWelfareMenuConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WelfareMenuConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WelfareMenuConfig> DataList => _dataList;

    public WelfareMenuConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WelfareMenuConfig Get(int key) => _dataMap[key];
    public WelfareMenuConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

