
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TipTextConfig : Luban.BeanBase
{
    public TipTextConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TType = _buf.ReadInt();
        Content = _buf.ReadString();
    }

    public static TipTextConfig DeserializeTipTextConfig(ByteBuf _buf)
    {
        return new TipTextConfig(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int TType;
    /// <summary>
    /// 内容
    /// </summary>
    public readonly string Content;
   
    public const int __ID__ = 1485202858;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tType:" + TType + ","
        + "content:" + Content + ","
        + "}";
    }
}

}

