
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TodayGiftConfig : Luban.BeanBase
{
    public TodayGiftConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TitleTxt = _buf.ReadString();
        DescTxt = _buf.ReadString();
        Commodity = _buf.ReadString();
        IconCtrl = _buf.ReadInt();
    }

    public static TodayGiftConfig DeserializeTodayGiftConfig(ByteBuf _buf)
    {
        return new TodayGiftConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中间描述
    /// </summary>
    public readonly string TitleTxt;
    /// <summary>
    /// 补充描述
    /// </summary>
    public readonly string DescTxt;
    /// <summary>
    /// 商品
    /// </summary>
    public readonly string Commodity;
    /// <summary>
    /// 宝箱图标
    /// </summary>
    public readonly int IconCtrl;
   
    public const int __ID__ = 1172245139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "titleTxt:" + TitleTxt + ","
        + "descTxt:" + DescTxt + ","
        + "commodity:" + Commodity + ","
        + "iconCtrl:" + IconCtrl + ","
        + "}";
    }
}

}

